### ISSUE TITLE
Resolving entities via rewriteURI/rewriteSystem

### ISSUE THREAD

**Issue by dwcramer** [ndw/xmlresolver#11]
I'm using xmlresolver from xmlcalabash. I've created a collection of xml content, entity files, a catalog, and a xproc pipeline to illustrate the problem here: https://github.com/dwcramer/xmlcalabash-catalog-bug

Give rules like the following in my `catalog.xml`:
```
    <rewriteURI uriStartString="file://docshared/" rewritePrefix="../"/>
    <rewriteSystem systemIdStartString="file://docshared/" rewritePrefix="../"/>
```
Calabash is able to resolve hrefs in xincludes that rely on the rule, but is unable to resolve an entity file, e.g.:
```
<!ENTITY % myents SYSTEM "file://docshared/entities/rewrite-this.ent" >
%myents;
```

Note that this might be related to: https://github.com/ndw/xmlcalabash1/issues/179

If I instead tell Calabash to use org.apache.xml.resolver.tools.CatalogResolver, it resolves `file://docshared/entities/rewrite-this.ent` just fine.

**Comment by ndw** [comment]
This was fixed by applying #2. My guess is that I had some weird bit of inconsistency that's now been resolved.
