### ISSUE TITLE
Parsing XML file that uses a DTD declared with a PUBLIC doesn't work.

### ISSUE THREAD

**Issue by cmarchand** [ndw/xmlresolver#12]
Hello,

this is related to [gaulois-pipe issue #39](https://github.com/cmarchand/gaulois-pipe/issues/39), but this should be declared here.

A xml file starts like this :
```
<!DOCTYPE data PUBLIC "GAULOIS//AWFUL" "/fakepath/awful.dtd">
```

I use a catalog like this :
```
<public publicId="GAULOIS//AWFUL" uri="src/test/resources/awfulDtd/awful.dtd"/>
```

Java code is :
```
Resolver resolver = new Resolver(new Catalog("src/test/resources/awfulDtd/awful-catalog.xml"));
SAXParserFactory factory = SAXParserFactory.newInstance();
SAXParser parser = factory.newSAXParser();
XMLReader reader = parser.getXMLReader();
reader.setEntityResolver(resolver);
reader.parse(new File("src/test/resources/awfulDtd/inputFile.xml").toURI().toURL().toString());
```

Resolver does not resolve the entity to the specified DTD file :
```
TRACE org.xmlresolver.Catalog - Default properties: XMLResolver.properties;CatalogManager.properties
DEBUG org.xmlresolver.Catalog - Loaded xmlresolver.properties from classpath: jar:file:/home/ext-cmarchand/.m2/repository/org/xmlresolver/xmlresolver/0.12.4/xmlresolver-0.12.4.jar!/xmlresolver.properties
TRACE org.xmlresolver.Resolver - resolveEntity([dtd],GAULOIS//AWFUL,file:/fakepath/awful.dtd)
TRACE org.xmlresolver.ResourceResolver - resolveEntity([dtd],file:/fakepath/awful.dtd,GAULOIS//AWFUL)
TRACE org.xmlresolver.Catalog - lookupEntity([dtd],GAULOIS//AWFUL,file:/fakepath/awful.dtd)
TRACE org.xmlresolver.Catalog - Parse URI: src/test/resources/awfulDtd/awful-catalog.xml
TRACE org.xmlresolver.Catalog - Looking in file:///home/ext-cmarchand/devel/github/resolver-bug/src/test/resources/awfulDtd/awful-catalog.xml
TRACE org.xmlresolver.Catalog - Found: org.xmlresolver.CatalogResult@cb644e
TRACE org.xmlresolver.Resolver - file:/fakepath/awful.dtd (GAULOIS//AWFUL) => file:/fakepath/awful.dtd
```
The whole project is attached, just run `mvn test`
[resolver-bug.zip](https://github.com/ndw/xmlresolver/files/2025748/resolver-bug.zip)

**Comment by cmarchand** [comment]
SOLVED.
I do not define an URI relative to catalog location, but relative to `${project.basedir}`

**Comment by ndw** [comment]
Hi Christophe. Sorry I didn't get to this before you did. (Or, conversely, "yay, you figured it out!")
Just to be clear, the URI in the catalog *works correctly* when it's relative to the catalog URI. The error was that you had put in a URI relative to the project basedir, yes?

**Comment by cmarchand** [comment]
Yes exactly. I was focused on JUnit test, in maven environment, with URI relatives to project basedir, and not focused on "this is XML technology, URI are relatives to the file that embed them" !
So, problem was again between chair and keyboard...

Sorry to be so noisy with such a simple problem.

**Comment by ndw** [comment]
Thank you, Christophe. Sorry for the confusion. If it's any consolation, almost all of my problems turn out to be PEBKAC.
