### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by philippn** [ndw/xmlresolver#14]
Hi there,

It appears to me that there are some dependencies marked as "compile", which are only needed for tests. In particular I am referring to junit.

Aside from Junit, there is also alot of Log4j dependencies. If the code in the Resolver is only using SLF4J API itself it would be preferable to include only the SLF4J API as compile dependency and leave it to the client application to choose which logging framework to use behind SLF4J.

Thanks in advance and keep up the good work!

**Comment by philippn** [comment]
Please find attached screenshot.
![dependencies](https://user-images.githubusercontent.com/445105/42287324-2f2631cc-7fb6-11e8-8c5e-958aa0323c86.png)

**Comment by ndw** [comment]
What do you think of #15 ?

**Comment by philippn** [comment]
I would recommend to keep the SLF4J Compile dependencies, because a) the Java code is directly using the SLF4J LoggerFactory and b) Apache HTTP client is using Commons Logging, which can be redirected to SLF4J as well by using the `jcl-over-slf4j` bridge.

Instead I would move all three Log4j2 dependencies into `testImplementation`. And while at it, I would also recommend to move the `log4j2.xml` file to `src/test/resources` instead of `src/main/resources` because Log4J is then only used during the tests.

**Comment by ndw** [comment]
It occurred to me after I sent that message, that there are some "main" executables in there that probably should be factored out of the library. And I might try to work out what modern best practices are for initializing loggers. Thanks. More in a bit.
