### ISSUE TITLE
Is org.xmlresolver.apps.Parse the new com.nwalsh.parsers.xjparse?

### ISSUE THREAD

**Issue by adelton** [ndw/xmlresolver#18]
Hello,

I've been investigating some issue with `xjparse` and have realized that Fedora 29 ships `xjparse-1.0-18.fc29.noarch` while the last commit in https://github.com/ndw/xjparse says "Version 2.0.1 released" six years ago. So I tried to build a new version of `xjparse` only to find out that it needs `org.xmlresolver` which is not packaged in Fedora (yet). That got me here.

Building from sources and running
```
java -cp ./core/build/libs/xmlresolver-0.14.0.jar:./apps/build/libs/xmlresolver-apps-0.14.0.jar:/usr/share/java/slf4j/api.jar:/usr/share/java/httpcomponents/httpcore.jar:/usr/share/java/httpcomponents/fluent-hc.jar:/usr/share/java/httpcomponents/httpmime.jar:/usr/share/java/httpcomponents/httpcore-nio.jar:/usr/share/java/httpcomponents/httpcore.jar:/usr/share/java/httpcomponents/httpclient.jar:/usr/share/java/junit.jar:/usr/share/java/slf4j/simple.jar org.xmlresolver.apps.Parse
```
says
```
Usage: com.nwalsh.parsers.xjparse [opts] xmlfile

Where:

-c catalogfile   Load a particular catalog file
-w               Perform a well-formed parse, not a validating parse
-v               Perform a validating parse (the default)
-s               Enable W3C XML Schema validation
-S schema.xsd    Use schema.xsd for validation (implies -s)
-f               Enable full schema checking (implies -s)
-n               Perform a namespace-ignorant parse
-N               Perform a namespace-aware parse (the default)
-E integer       Set the maximum number of errors to display

The process ends with error-level 1, if there are errors.
```
which looks very much as the output from that old `xjparse` version, except for one important thing -- the `-d` option is not listed, and it does nothing.

What is the plan of `xjparse` and `xmlresolver`? Will they continue living independently, `xmlresolver` only being a library? Or will `org.xmlresolver.apps.Parse` get the full `xjparse` functionality, specifically that `-d`?

I ask primarily to know what to plan for from Fedora packaging point of view but to also know if changes like
```
sed -i 's/com.nwalsh.parsers.xjparse/org.xmlresolver.apps.Parse/' apps/src/main/java/org/xmlresolver/apps/Parse.java
```
is something you'd be interested in.

**Comment by ndw** [comment]
I want to do a 1.0 release of the resolver; let me take a look at this little tangle.
My guess is that the bundled xjparse is just a much simpler smoke test of the library.

**Comment by ndw** [comment]
No. I've tidied up `xjparse` and simpilfied what's in `xmlresolver` in the hopes of making it clearer.
