### ISSUE TITLE
xmlresolver.properties should not be packaged in xmlresolver jar file

### ISSUE THREAD

**Issue by cmarchand** [ndw/xmlresolver#21]
Hi Norm,

When using xmlresolver in a maven project, I'm able to define a `xmlresolver.properties` in `src/main/resources` to package it in my application.
But when Maven constructs the classpath, there is no guarantee that my `xmlresolver.properties` is *before* xmlresolver's one, and so, there is no guarantee I'll be able to override default configuration.

xmlresolver should keep its `xmlresolver.properties` in another classpath entry than `/xmlresolver.properties`, and load it *only if there is no* `xmlresolver.properties` defined in classpath.

**Comment by ndw** [comment]
And you couldn't have mentioned this a week ago because why? 😄 

Yes, I think you're right. 1.0.1 coming up soonish.

**Comment by cmarchand** [comment]
I knew you'll answer this... But I just felt on this problem this morning...
Sorry about that,
Christophe

**Comment by cmarchand** [comment]
But your new documentation is pretty beautiful !

**Comment by ndw** [comment]
I concur that simply removing the `xmlresolver.properties` file is all that is necessary. The default values for all of the properties named in that file were the same as the values in that file.

Could you please sanity check https://github.com/ndw/xmlresolver/pull/22 for me?
