### ISSUE TITLE
StAXResolver throws NullPointerException

### ISSUE THREAD

**Issue by nzhiv** [ndw/xmlresolver#24]
Hi,
StAXResolver throws NullPointerException for `<!DOCTYPE ONIXmessage SYSTEM "ONIX_BookProduct_3.0_short.dtd">` although Resolver used by SAXParser works fine for the same document.
I checked the code and it looks that the local variable **absSystem** in _resolveEntity(String publicId, String systemId, String baseURI, String namespace)_ method should be initialized to **systemId**.

       public Object resolveEntity(String publicId, String systemId, String baseURI, String namespace) throws XMLStreamException {
        // We can do better than this, but for now...just get an absolute URI
        String absSystem = null;

**Comment by ndw** [comment]
That seems reasonable to me.
