### ISSUE TITLE
Document migration path from Apache XML Resolver

### ISSUE THREAD

**Issue by jelovirt** [ndw/xmlresolver#30]
Documentation on how to migrate from Apache XML Resolver to using xmlresolver would be helpful. The xmlresolver.org website instructs using `Resolver` and how to set up properties files and system variables, but I'm looking for instructions how to replace the old `CatalogManager` and setting it up directly with setters.

**Comment by ndw** [comment]
See https://github.com/ndw/resolver-migration

If that's not sufficient, please open an issue there describing what is still unclear and I'll try to clarify.
