### ISSUE TITLE
rewriteSystem does not work

### ISSUE THREAD

**Issue by cmarchand** [ndw/xmlresolver#8]
Creating a catalog with this :
<rewriteSystem systemIdStartString="foo:" rewritePrefix="http://example.com/entity/"/>
Lookup doesn't work, as xmlresolver looks for a @uriStartString
Patch available at https://github.com/cmarchand/xmlresolver/tree/rewriteSystem

**Comment by ndw** [comment]
Fixed by pull #7 yes?

**Comment by cmarchand** [comment]
Fixed. Thanks
