### ISSUE TITLE
InputStreams are not closed 

### ISSUE THREAD

**Issue by kal0ian** [ndw/xmlresolver#9]
In CatalogManager class at line 244, DOMCatalogReader class at line 241, Resolver class at line 378, SAXCatalogReader at line 212 InputStream is opened and it is not closed.

**Comment by ndw** [comment]
Most of those classes are gone now. The remaining use in Resolver looks harmless. If you ask for the stream, I think you have to close it. (There doesn't seem to be anywhere to close it.)
